# Generated by Django 4.2.6 on 2023-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('date', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=64)),
            ],
        ),
    ]
