# Generated by Django 4.2.7 on 2024-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='q1',
            field=models.CharField(max_length=24),
        ),
    ]
