# Generated by Django 4.2.7 on 2024-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reviews_name_reviews_q7_alter_reviews_q1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectBuilding', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
